


package discotheque;

import java.awt.BorderLayout;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.util.Vector;
import oracle.jdbc.driver.OracleConnection;

public class JFrameListeArtiste extends javax.swing.JFrame {

    /**
     * Creates new form JFrameListeArtiste
     */
    public JFrameListeArtiste(ConnectionOracle conn, int numArt) {
        initComponents();
        this.connBD = conn;
        this.numArtiste = numArt;
    }

    
    public void lister(){
    
        Vector vectDisques = new Vector();
        Vector vectEntete = null;
        JTable tabDisques = null;
        try
        {
            PreparedStatement stm = connBD.getConnection().prepareStatement(sqlListe);
            stm.setInt(1, numArtiste);
            ResultSet rst = stm.executeQuery();
            vectDisques = remplirVecteur(rst);
            vectEntete = creerEntete();  
            tabDisques = new JTable(vectDisques, vectEntete);
            JSP_Artistes.setViewportView(tabDisques);
            this. getContentPane().add(JSP_Artistes,BorderLayout.CENTER);
            JSP_Artistes.validate();            
        }
        catch(SQLException se)
        {
            JOptionPane.showMessageDialog(this, se);
        }
    }
    
    private Vector creerEntete()
    {
        Vector vectEntete = new Vector();
        vectEntete.add("No Disque");
        vectEntete.add("Titre");
        vectEntete.add("Prix");
        vectEntete.add("Année");
        vectEntete.add("Lanque");
        vectEntete.add("Nbre chansons");
        vectEntete.add("Genre");
        return vectEntete;        
    }
    private Vector remplirVecteur(ResultSet rst){
        Vector v = new Vector();
        Vector ligne = null;
        try
        {            
            while (rst.next()){
                ligne = new Vector();
                ligne.add(rst.getInt(1));
                ligne.add(rst.getString(2));
                ligne.add(rst.getFloat(3));
                ligne.add(rst.getInt(4));
                ligne.add(rst.getString(5));
                ligne.add(rst.getInt(6));
                ligne.add(rst.getString(7));
                v.add(ligne); 
            }            
        }
        catch (SQLException se)
        {
            JOptionPane.showMessageDialog(this, se);
        }
        return v;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JSP_Artistes = new javax.swing.JScrollPane();

        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(JSP_Artistes, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSP_Artistes, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListeArtiste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListeArtiste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListeArtiste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListeArtiste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
 //               new JFrameListeArtiste(connBD).setVisible(true);
            }
        });
    }

    int numArtiste = 0;
    ConnectionOracle connBD;
    String sqlListe = "select * from disques where numdisque in " +
            "(select numdisque from \"Artiste/Disque\" where numart = ? )";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JSP_Artistes;
    // End of variables declaration//GEN-END:variables
}
